server:
  port: ${PORT:0}
spring:
  application:
    name: account-app
  datasource:
    url: jdbc:mysql://54.82.8.131:3307/accounts
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'